#include <iostream>
#include <string.h>

using namespace std;

/*
    Function Templates

    1. Introduction to function templates
    2. Trying out function templates
    3. Template type deduction and explicit arguments
    4. Template parameters by reference
    5. Template specialization
    6. Different Type Names
*/



/*
    1. Code repetition when overloading functions
*/ 

int max(int a, int b) {
    return (a > b) ? a : b;
}

double max(double a, double b) {
    return (a > b) ? a : b;
}

string max(string a, string b) {
    return (a > b) ? a : b;
}

/*
    Avoiding code repetition.
    Here's an example of a simple function template that returns the maximum of two values:
*/

template <typename T> T max (T a, T b) {
    return (a > b) ? a : b;
}


/*
    Or we can declare our template function and then implement it
*/

// Declaration
template <typename T> T maximum(T, T);

// Implementation
template <typename T> T maximum(T a, T b) {
    return (a > b) ? a : b;   // a and b sould support the '>' operator.
}



/*
    4. Template parameters by reference
*/
template <typename T> T maximum_1(T a, T b) {
    cout << "In - &a: " << &a << endl;   // Ex: 0x7ffe486afb4c
    return (a > b) ? a : b;   
}

template <typename T> const T &maximum_2(const T &a, const T &b) {
    cout << "In - &a: " << &a << endl;   // Ex: 0x7ffdcd6be7c8
    return (a > b) ? a : b;
}

// The same template function maximum_2 but without reference type
// But it will cause compile time error, because compiler will not be able to determine which maximum_2 function to call
template <typename T> T maximum_2(T a, T b) {   
    cout << "In - &a: " << &a << endl;   // Ex: 0x7ffdcd6be7c8
    return (a > b) ? a : b;
}



/*
    5. Template specialization
*/
template <typename T> T maximum(T a, T b) {
    return (a > b) ? a : b;
}


/*
    6. Different Type Names
*/
template <typename T, typename D> T maximum (D a, D b) {
    return (a > b) ? a : b;
}




int main() {

    /*
        1. Introduction to function templates

        In C++, a function template is a way to create a generic function that can work with different data types. 
        It allows you to define a function without specifying the exact type(s) of its parameters or return value.
        Instead, you use placeholders or type parameters, represented by the keyword "typename" or "class", 
        to indicate the generic type(s) that will be used when the function is called.
    */

    int a = 23;
    int b = 10;

    double c = 34.7;
    double d = 23.5;

    string e = "Hello";
    string f = "World";

    cout << "maximum(int) :    " << maximum(a, b) << endl;
    /*
        maximum(a, b) call will generate real C++ function like:
        int maximum<int>(int a, int b)
        {
            return (a > b) ? a : b;
        }
    */
    cout << "maximum(double) : " << maximum(c, d) << endl;
    /*
        maximum(a, b) call will generate real C++ function like:
        double maximum<double>(double a, double b)
        {
            return (a > b) ? a : b;
        }
    */
    cout << "maximum(string) : " << maximum(e, f) << endl;
    /*
        maximum(a, b) call will generate real C++ function like:
        std::basic_string<char> maximum<std::basic_string<char> >(std::basic_string<char> a, std::basic_string<char> b)
        {
            return std::basic_string<char>((std::operator>(a, b)) ? a : b);
        }
    */
    

    long long int x(5);
    long long int y(6);
    int result = maximum(x, y);
    /*
        This call will generate:
        long long int maximum<long long int>(long long int a, long long int b)
        {
            return (a > b) ? a : b;
        }
    */


    auto reslt1 = maximum(a, b);
    /*
        This call will generate:
        int maximum<int> (int a, int b)
        {
            return (a > b) ? a : b;
        }
    */


    /*
        Overview:

        ~ Function templates are just blueprints. They're not real C++ code consumed by the compiler.
          The compiler generates real C++ code by looking at the arguments you call your function template with.

        ~ The real C++ function generated by the compiler is called a template instance

        ~ A template instance will be reused when a similar function call (argument types) is issued.
          No duplicates are generated by the compiler.

        Test to see template instance generated by compiler: 
        Source: https://cppinsights.io/
    */


    /*
        Summary: 

        1. Function templates are just blueprints, not real declarations and definitions functions.

        2. Real function declarations and definitions, also known as template instances,
        are created when a function is called with arguments.

        3. If the template parameters are of the same type (T, T), then the arguments with which you call the function
        must also match, otherwise you will get a compiler error.

        4. Template instances won't always do what you want. A good example is when you call
        our maximum function with pointers. CATASTROPHE!

        5. There are tools like cppinsights.io that can show you template instances.
        You can even use a debugger to infer this information from the activation entry
        template functions.

        6. Arguments passed to a function template must support operations functions performed in the body.
    */






    /*
        3. Template type deduction and explicit arguments
    */

    maximum(a, b);    // int type deduced
    maximum(c, d);    // double type deduced
    maximum(e, f);    // string type deduced

    maximum<double>(c, d);   // explicitly say that we want double
    maximum<double>(a, c);   // works, even if parametersare of different types (will be implicit conversion)
    maximum<double>(a, e);   // Error: can't convert "string" to double

    auto max = maximum(a, d);   
    // Error: a is integer type, d is double type but "template <typename T> T maximum(T a, T b)" - as you see here
    // maximum template function takes two arguments with the same type "T"

    // We can fix it by Explicit template arguments
    auto max = maximum<double>(a, d);   // It will implicitly convert a and b to double type
    cout << "max: " << max << endl;





    /*
        4. Template parameters by reference
    */

    int a = 12;
    int b = 13;

    cout << "Out - &a : " << &a << endl;    // Ex: 0x7ffe486afb6c
    int max1 = maximum_1(a, b);
    cout << "max1: " << max1 << endl;

    cout << "Out - &a : " << &a << endl;    // Ex: 0x7ffdcd6be7c8
    int max2 = maximum_2(a, b);
    cout << "max1: " << max2 << endl;
    /*
        Genereted template instance: 
        
        const int & maximum_2<int>(const int & a, const int & b)
        {
            std::operator<<(std::cout, "In - &a: ").operator<<(reinterpret_cast<const void *>(&a)).operator<<(std::endl);
            return (a > b) ? a : b;
        }
    */




    /*
        5. Template specialization
    */
    int a = 1;
    int b = 2;
    double c = 1.1;
    double d = 2.2;
    string e = "three";
    string f = "four";

    int max_int = maximum(a, b);          // int type deduced
    double max_double = maximum(c, d);    // double type deduced
    string max_string = maximum(e, f);    // string type deduced


    // 6. Different Type Names

    unsigned long int a = 5;
    unsigned long int b = 5;

    cout << maximum<char>(5.2, 88.5) << endl;
    cout << maximum<float>(5.2, 8.2) << endl;
    cout << maximum<short int>(a, b) << endl;
    
}